- name: Install build tools
  yum:
    name: "@Development tools"
    state: present
  become: yes

- name: install openssl-devel
  become: yes
  package:
    name: openssl-devel
    state: latest

#- name: install tpm2-tools
  #become: yes
  #package:
    #name: tpm2-tools
    #state: latest

#- name: install tpm2-abrmd
  #become: yes
  #package:
    #name: tpm2-abrmd
    #state: latest

#- name: install tpm2-tss
  #become: yes
  #package:
    #name: tpm2-tss
    #state: latest

- name: install tboot
  become: yes
  package:
    name: tboot
    state: latest

