- name: Build tpm2-tss
  become: yes
  shell: 'chdir=/root/tpm2-tss "{{ item }}"'
  with_items:
    - make clean
    - ./bootstrap
    - ./configure --enable-unit --enable-integration
    - make -j4 check
    - make install

- name: Build tpm2-abrmd
  become: yes
  shell: 'chdir=/root/tpm2-abrmd "{{ item }}"'
  with_items:
    - make clean
    - ./bootstrap
    - ./configure --enable-unit --with-dbuspolicydir=/etc/dbus-1/system.d
    - make -j4 check
    - make install

- name: Build tpm2-tools
  become: yes
  shell: 'chdir=/root/tpm2-tools "{{ item }}"'
  with_items:
    - make clean
    - ./bootstrap
    - ./configure --enable-unit --enable-integration
    - make -j4 check
    - make install
