- name: Set LD_LIBRARY_PATH environment
  become: yes
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: '^LD_LIBRARY_PATH'
    line: 'LD_LIBRARY_PATH=/usr/lib'

- name: Add the user 'tss'
  become: yes
  user:
    name: tss
    comment: TPM2 TSS User
    group: tss
    shell: /bin/bash

- name: SELinux to permissive
  become: yes
  selinux:
    policy: targeted
    state: permissive

# tpm2-tss
- name: bootstrap tpm2-tss
  become: yes
  command: ./bootstrap
  args:
    chdir: "/root/tpm2-tss/"

- name: configure tpm2-tss
  become: yes
  shell: "{{tpm2_tss_configure_args }}"
  args:
    chdir: "/root/tpm2-tss/"
  environment:
    PATH: /root/ibmtpm974/src:{{ ansible_env.PATH }}

- name: Make check tpm2-tss
  become: yes
  command: make
  args:
    chdir: "/root/tpm2-tss/"

- name: Make install tpm2-tss
  become: yes
  command: make install
  args:
    chdir: "/root/tpm2-tss/"

# tpm2-abrmd

- name: bootstrap tpm2-abrmd
  become: yes
  command: ./bootstrap
  args:
    chdir: "/root/tpm2-abrmd/"

- name: configure tpm2-abrmd
  become: yes
  shell: "{{tpm2_abrmd_configure_args }}"
  args:
    chdir: "/root/tpm2-abrmd/"
  environment:
    PATH: /root/ibmtpm974/src:{{ ansible_env.PATH }}

- name: Make check tpm2-abrmd
  become: yes
  command: make
  args:
    chdir: "/root/tpm2-abrmd/"

- name: Make install tpm2-tss
  become: yes
  command: make install
  args:
    chdir: "/root/tpm2-abrmd/"

# tpm2-tools

- name: bootstrap tpm2-tools
  become: yes
  command: ./bootstrap
  args:
    chdir: "/root/tpm2-tools/"

- name: configure tpm2-tools
  become: yes
  shell: "{{ tpm2_tools_configure_args }}"
  args:
    chdir: "/root/tpm2-tools/"
  environment:
    PATH: /root/ibmtpm974/src:{{ ansible_env.PATH }}

- name: Make check tpm2-tools
  become: yes
  command: make
  args:
    chdir: "/root/tpm2-tools/"

- name: Make install tpm2-tools
  become: yes
  command: make install
  args:
    chdir: "/root/tpm2-tools/"

- name: Add lib to ld.so.conf
  become: yes
  lineinfile: dest=/etc/ld.so.conf line="/usr/lib/"

- name: Run ldconfig
  become: yes
  command: /sbin/ldconfig

- name: Amend systemd for tpm2-abrmd ExecStart
  become: yes
  lineinfile:
    dest: /usr/lib/systemd/system/tpm2-abrmd.service
    state: present
    regexp: '^ExecStart'
    line: 'ExecStart=/usr/sbin/tpm2-abrmd --tcti=libtss2-tcti-mssim.so'

- name: Amend systemd for tpm2-abrmd Environment
  become: yes
  lineinfile:
    dest: /usr/lib/systemd/system/tpm2-abrmd.service
    state: present
    regexp: '^EnvironmentFile'
    line: 'EnvironmentFile=/etc/environment'
